version: '2.23.3'

services:
  user-service:
    image: adsservice:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

  confirmation-service:
    image: transactionservice:latest
    ports:
      - "8083:8083"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
